urand – Pikaia
urand Function
Jacob Williams
3/8/2015
5 statements
Source File
private function urand() result(r)
Return the next pseudo-random deviate from a sequence which is uniformly distributed in the interval [0,1]
Note
This is now just a wrapper for the intrinsic random_number function.
Arguments
None
Return Value real(kind=wp)
Called by
Contents
Source Code
urand
Source Code
    function urand() result(r)
    implicit none
    real(wp) :: r
    call random_number(r)
    end function urand
Call graph
pikaia calls urand
cross calls urand
mutate calls urand
select_parents calls urand
stdrep calls urand